application: cg-dogcollars2
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /data
  static_dir: data

- url: /images
  static_dir: images

- url: /lib
  static_dir: lib

- url: /styles
  static_dir: styles

- url: /scripts
  static_dir: scripts

- url: /scripts/directives
  static_dir: scripts/directives

- url: /scripts/controllers
  static_dir: scripts/controllers

- url: /views
  static_dir: views

- url: /
  static_files: index.html
  upload: index.html

- url: /_ah/spi/.*
  script: rivet_api.application

libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: latest
