application: your-app-id
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
# Endpoints handler
- url: /_ah/spi/.*
  script: rivet_api.application
  
- url: /data
  static_dir: data

- url: /images
  static_dir: images

- url: /lib
  static_dir: lib

- url: /scripts
  static_dir: scripts

- url: /styles
  static_dir: styles

- url: /views
  static_dir: views

- url: /
  static_files: index.html
  upload: static/HTML/index.html

libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0
